version: '3.2'

services:
  statediffing-geth:
    build:
      context: ./../../
      cache_from:
      - alpine:latest
      - golang:1.13
      dockerfile: ./dockerfiles/geth/Dockerfile
    expose:
    - "8545"
    - "8546"
    ports:
    - "127.0.0.1:8545:8545"
    - "127.0.0.1:8546:8546"
    command: ["--syncmode", "full",
              "--statediff",
              "--ws",
              "--cache", "4096",
              "--cache.database", "50",
              "--cache.gc", "50",
              "--rpc",
              "--rpcapi", "eth,statediff,net"]

  super-node-db:
    restart: always
    image: postgres:10.12-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "vulcanize_public"
      POSTGRES_PASSWORD: "password"
    volumes:
    - vulcanizedb_db_data:/var/lib/postgresql/data
    expose:
    - "5432"
    ports:
    - "127.0.0.1:8079:5432"

  ipfs-btc-watcher:
    depends_on:
    - super-node-db
    build:
      context: ./../../
      cache_from:
      - alpine:latest
      - golang:1.13
      dockerfile: ./dockerfiles/super_node/Dockerfile
      args:
        USER: "vdm"
        CONFIG_FILE: ./environments/superNodeBTC.toml
    environment:
      VDB_COMMAND: "watch"
      DATABASE_NAME: "vulcanize_public"
      DATABASE_HOSTNAME: "db"
      DATABASE_PORT: 5432
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "password"
    ports:
    - "127.0.0.1:8082:8082"
    - "127.0.0.1:8083:8083"

  ipfs-eth-watcher:
    depends_on:
    - super-node-db
    build:
      context: ./../../
      cache_from:
      - alpine:latest
      - golang:1.13
      dockerfile: ./dockerfiles/super_node/Dockerfile
      args:
        USER: "vdm"
        CONFIG_FILE: ./environments/superNodeETH.toml
    environment:
      VDB_COMMAND: "watch"
      DATABASE_NAME: "vulcanize_public"
      DATABASE_HOSTNAME: "db"
      DATABASE_PORT: 5432
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "password"
    ports:
    - "127.0.0.1:8080:8080"
    - "127.0.0.1:8081:8081"

  super-node-graphql:
    restart: always
    depends_on:
    - super-node-db
    build:
      context: ./../../
      cache_from:
      - node:alpine
      dockerfile: ./dockerfiles/postgraphile/Dockerfile
    expose:
    - "5000"
    ports:
    - "127.0.0.1:5000:5000"
    command: ["--plugins", "@graphile/pg-pubsub",
              "--subscriptions",
              "--simple-subscriptions",
              "--connection", "postgres://postgres:password@super-node-db:5432/vulcanize_public",
              "--port", "5000",
              "-n", "0.0.0.0",
              "--schema", "public,btc,eth",
              "--append-plugins", "postgraphile-plugin-connection-filter"]

volumes:
  vulcanizedb_db_data:
